name: riery_packages

description: A monorepo containing multiple packages for Riery. All the code as made by Coespy. https://github.com/Coaspe/riot_apim. This is only a training for me.

environment:
  sdk: ^3.0.0
